<%@ Page Language="C#" AutoEventWireup="true" CodeFile="showUsers.aspx.cs" Inherits="showUsers" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body style="background-color:whitesmoke">
    <form id="form1" runat="server">
    <div>
    
    </div>
        <asp:Label ID="Label1" runat="server" Text="Hello.." ForeColor="Yellow" Font-Size="X-Large" Font-Bold="True"></asp:Label>
        <br /><asp:Label ID="Label2" runat="server" Text="Following is the list of registered users.." ForeColor="Red" Font-Size="X-Large" Font-Bold="True"></asp:Label>
        <br /><br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" BackColor="#333333" BorderStyle="Solid" BorderWidth="4px" CellPadding="2" CellSpacing="1" DataKeyNames="Id" DataSourceID="SqlDataSource1" Font-Bold="False" ForeColor="Yellow" Height="950px" Width="100%" AllowPaging="True">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
            </Columns>
<EmptyDataTemplate>
Id
</EmptyDataTemplate>
            <PagerStyle Font-Bold="True" Font-Size="X-Large" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:MediDB %>" ProviderName="<%$ ConnectionStrings:MediDB.ProviderName %>" SelectCommand="SELECT * FROM [Login]"></asp:SqlDataSource>

    </form>
</body>
</html>
